// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oqquvawbhubibjyuxpkg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9xcXV2YXdiaHViaWJqeXV4cGtnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzODgwMDIsImV4cCI6MjA1OTk2NDAwMn0.o1lnLP_JNRW7VHwfvu9qkBosIcZcKRJ-btj7KeGqlZg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);